# Publication a new text
POST http://localhost:3000/api/text/publication HTTP/1.1
Content-Type: application/json

{
  "namePublication": "Я в гор",
  "announcementPublication": "Как провел отпуск в горной Архызе",
  "textPublication": "Это было не забываемо. Советую",
  "setTag": "#Горы",
  "authorPublication": "Serg"
}

###

# Get text by ID
# 1-это id Текст
GET http://localhost:3000/api/text/1 HTTP/1.1

###

# Delete text by ID
# 1-это id Текст
DELETE  http://localhost:3000/api/text/1 HTTP/1.1

###

# Upgrade text by ID
# 1-это id Текст
PATCH   http://localhost:3000/api/text/1 HTTP/1.1
Content-Type: application/json

{
  "namePublication": "Я среди гор",
  "announcementPublication": "Как провел выходные в Домбай",
  "textPublication": "Это было не забываемо, много горных экотроп. Советую",
  "setTag": "#Горы",
  "authorPublication": "Vlad"
}
