# Publication a new video
POST http://localhost:3000/api/video/publication HTTP/1.1
Content-Type: application/json

{
  "namePublication": "Я среди гор",
  "linkVideo": "http://month",
  "setTag": "#Горы",
  "authorPublication": "Vlad"
}

###

# Get video by ID
GET http://localhost:3000/api/video/1 HTTP/1.1

###

# Delete video by ID
DELETE  http://localhost:3000/api/video/1 HTTP/1.1

###

# Upgrade video by ID
PATCH   http://localhost:3000/api/video/1 HTTP/1.1
Content-Type: application/json

{
  "namePublication": "Я среди гор",
  "linkVideo": "http://localhost:4000/month",
  "setTag": "#Горы",
  "authorPublication": "Vlad"
}
