# Create a new user
POST http://localhost:4500/api/user/register HTTP/1.1
Content-Type: application/json

{
  "email": "alex.v@yandex.ru",
  "firstName": "Alexs",
  "password": "Volga34",
  "avatar": "66e1a8ab87570b7425c6dec0"
}

###

# Get user by ID
GET http://localhost:4500/api/user/register/66cd70fe08e4005f86d14736 HTTP/1.1
