# Authorization user
POST http://localhost:3000/api/user/authorization HTTP/1.1
Content-Type: application/json

{
  "email": "user@notfound.local",
  "password": "1234"
}

###

# Chang user password
PATCH  http://localhost:3000/api/user/authorization/1e1a9523-ce1c-46ac-86f6-f92852f65e8a HTTP/1.1
Content-Type: application/json

{
  "password": "123456",
  "newPassword": "1984"
}
