# Add comment
POST   http://localhost:3000/api/comment/9bbd4bf9-4055-402f-bddc-6cbaa352fea1 HTTP/1.1
Content-Type: application/json

{
  "text": "Good trip",
  "authorComment": "GGG"
}

###

# Get list of comments
GET http://localhost:3000/api/comment/list HTTP/1.1
Content-Type: application/json

{
  "idList": [
    "fd9867cc-8959-4aa9-b0ee-ee455540ff2e"
  ]
}

###

# Delete comment
DELETE  http://localhost:3000/api/comment/delete HTTP/1.1
Content-Type: application/json

{
  "idList": [
    "fd9867cc-8959-4aa9-b0ee-ee455540ff2e"
  ]
}
