# Get list publications
GET http://localhost:4000/api/publications/list HTTP/1.1
Content-Type: application/json

{
  "authPublication": "Vlad"
}

###

# Get a list of unpublished publication
GET http://localhost:4000/api/publications/drafts?author=Vlad HTTP/1.1
Content-Type: application/json

{
  "author": "Vlad"
}
