# Authorization user
POST http://localhost:4000/api/user/authorization HTTP/1.1
Content-Type: application/json

{
  "email": "vlad@v.com",
  "password": "1984Volga"
}

###

# Chang user password
PATCH  http://localhost:4000/api/user/authorization/66cd70fe08e4005f86d14736 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cXVCJ9.eyJpZCI6IjY2Y2Q3MGZlMDhlNDAwNWY4NmQxNDczNiIsImVtYWlsIjoidmxhZEB2LmNvbSIsImZpcnN0TmFtZSI6IlZsYWQiLCJhdmF0YXIiOiJ2bGFkLmpwZWciLCJpYXQiOjE3MjQ3NjI0MDMsImV4cCI6MTcyNDc2MzYwM30.9-kJ7l-LofWzCsA4F4MxYhvejdMfu56-Sxxft1VVDO0

{
  "password": "1984Volga",
  "newPassword": "Volga34"
}
