# Authorization user
POST http://localhost:4500/api/user/authorization HTTP/1.1
Content-Type: application/json

{
  "email": "alex.v@yandex.ru",
  "password": "Volga34"
}

###

# Chang user password
PATCH  http://localhost:4000/api/user/authorization/66cd70fe08e4005f86d14736 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2Q3MGZlMDhlNDAwNWY4NmQxNDczNiIsImVtYWlsIjoidmxhZEB2LmNvbSIsImZpcnN0TmFtZSI6IlZsYWQiLCJhdmF0YXIiOiJ2bGFkLmpwZWciLCJpYXQiOjE3MjU2MDc3MDQsImV4cCI6MTcyNTYwODkwNH0.ReWjyAgo2dsO1Kpbqrn0tfpaFK89YLXM3J39pGXpG4E

{
  "password": "Volga34",
  "newPassword": "V34Vlad"
}
