# Publication a new link
POST http://localhost:4000/api/link/publication HTTP/1.1
Content-Type: application/json

{
  "link": "https://nx.dev/nx-api/nest/generators/controller",
  "description": "Позновательно",
  "setTag": ["Горы"],
  "authorLink": "Alex"
}

###

# Get link by ID
GET http://localhost:4000/api/link/1 HTTP/1.1

###

# Delete link by ID
DELETE  http://localhost:4000/api/link/1 HTTP/1.1

###

# Upgrade link by ID
PATCH   http://localhost:4000/api/link/1 HTTP/1.1
Content-Type: application/json

{
  "link": "https://kartinki.pics/pics/uploads/posts/2022-08/1659605503_11-kartinkin-net-p-podnozhie-gor-priroda-krasivo-foto-11.jpg",
  "description": "Величие природы",
  "setTag": ["Горы"],
  "authorPhoto": "Vlad"
}
