# Add comment
POST   http://localhost:3000/api/comment/create HTTP/1.1
Content-Type: application/json

{
  "text": "Good trip",
  "authorComment": "Tany",
  "idVideo": 2,
  "idText": 0
}

###

# Get list of comments
GET http://localhost:3000/api/comment/list HTTP/1.1
Content-Type: application/json

{
  "idPost": 2
}

###

# Delete comment
DELETE  http://localhost:3000/api/comment/delete HTTP/1.1
Content-Type: application/json

{
  "idPost": 1,
  "authorComment": "Tany"
}
