# Add comment
POST   http://localhost:4000/api/comment/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTUzNzQyN2NmYzhlNDJjOTQxZjEyMiIsImVtYWlsIjoiYWxleHMudkB5YW5kZXgucnUiLCJmaXJzdE5hbWUiOiJBbGV4cyIsImF2YXRhciI6InZsYWQuanBlZyIsImlhdCI6MTcyNjMwMjQ5MCwiZXhwIjoxNzI2MzAzNjkwfQ.7gliaxzYW6_CCwVsu7EnDKwHf-av5JRdfHZM-Ck7Xrs

{
  "text": "I love it and my live, whot about yuor",
  "idVideo": 3
}

###

# Get list of comments
GET http://localhost:4000/api/comment/list HTTP/1.1
Content-Type: application/json

{
  "idPost": 1
}

###

# Delete comment
DELETE  http://localhost:4000/api/comment/delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2ZTFhOGFiODc1NzBiNzQyNWM2ZGVjMCIsImVtYWlsIjoidjRua292LnZAeWFuZGV4LnJ1IiwiZmlyc3ROYW1lIjoiVmxhZCIsImF2YXRhciI6InZsYWQuanBlZyIsImlhdCI6MTcyNjIxMjcxNywiZXhwIjoxNzI2MjEzOTE3fQ.0IdB7kyqk2URl2o5SrHJDqkZEmLZa8KgRv5fRQ9VALQ

{
  "idPost": 2
}
