# Add comment
# В объекте третий ключ от верху может быть {idVideo, idText, idQuote, idPhoto, idLink}, а значением ключа id публикации.
POST   http://localhost:3000/api/comment/create HTTP/1.1
Content-Type: application/json

{
  "text": "Good trip",
  "authorComment": "Tany",
  "idPhoto": 1
}

###

# Get list of comments
# В idPost значение id публикации
GET http://localhost:3000/api/comment/list HTTP/1.1
Content-Type: application/json

{
  "idPost": 1
}

###

# Delete comment
# В idPost значение id публикации
DELETE  http://localhost:3000/api/comment/delete HTTP/1.1
Content-Type: application/json

{
  "idPost": 2,
  "authorComment": "Tany"
}
