# Publication a new photo
POST http://localhost:3000/api/photo/publication HTTP/1.1
Content-Type: application/json

{
  "photo": "photo.jpg",
  "setTag": "#Горы",
  "authorPhoto": "Nina"
}

###

# Get photo by ID
# 1-это id Фото
GET http://localhost:3000/api/photo/1 HTTP/1.1

###

# Delete photo by ID
# 1-это id Фото
DELETE  http://localhost:3000/api/photo/1 HTTP/1.1

###

# Upgrade photo by ID
# 1-это id Фото
PATCH   http://localhost:3000/api/photo/1 HTTP/1.1
Content-Type: application/json

{
  "photo": "mountains.jpg",
  "setTag": "#Горы, #Архыз",
  "authorPhoto": "Vlad"
}
